site_name: NOAA PMEL Overview qPCR Assay Design Workflow Overview
theme:
  name: readthedocs
  highlightjs: true
extra_css: [style_2.css]
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Home: 'index.md'
  - 'Assemble Existing Data': '01_Assemble_Existing_data.md'
  - 'Sequence DNA Gaps': '02_Sequence_DNA_Gaps.md'
  - 'Assemble Mitogenomes for target and congeners': '03_Assemble_Mitogenomes_for_target_and_congeners.md'
  - 'Design Putative Assay': '04_Design_Putative_Assay.md'
  - 'Test on tissues': '05_Test_on_tissues.md'
  - 'Determine LoD  & LoQ': '06_Determine_LoD_LoQ.md'
  - 'Test in mesocosm': '07_Test_in_mesocosm.md'
  - 'Test in field': '08_Test_in_field.md'
  - 'Pair with visual surveys': '09_Pair_with_visual_surveys.md'
  - 'Discussion Forum (external)': "https://github.com/orgs/NOAA-Omics/discussions"
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: "#"
